title: Homepage of Guobiao Mei
author: Guobiao Mei
description: Computer Scientist, Software Engineer and Manager
google_analytics: G-2R4HQKYW40
email: contact@gmei.dev
linkedin_username: guobiao
theme: jekyll-theme-hacker
show_downloads: false
exclude:
  - CNAME
  - README.md
